<head>
	<title>Testing API</title>
	<link rel="stylesheet" type="text/css" href="css/jqueryOA.css">
</head>

<body style="z-index:0;font-family:'Arial';font-size:10px;margin:auto;background-image:linear-gradient(#3366FF, #001DBF);background-image:-moz-linear-gradient(#3366FF, #001DBF);background-image:-webkit-gradient(linear, #3366FF, #001DBF);background-image:-ms-linear-gradient(#3366FF, #001DBF);">
	<table style="margin:auto;width:100%;height:100%;">
		<tr>
			<td style="margin:auto;width:100%;height:100%;text-align:center;">
				<center><h1 style="color:white;">JQuery Online Alert Testing Buttons</h1>
					<button style="background-color:red;color:white;padding:1em;width:600px;" onClick="getOA('danger|Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras in massa id lacus porta posuere. Nulla suscipit eget orci a facilisis. Sed feugiat interdum nibh vel bibendum. Nam condimentum ornare ante eget laoreet. Ut iaculis sem eu nibh porttitor vehicula. Vivamus nunc massa, accumsan at sodales vel, suscipit quis arcu. Vestibulum ac accumsan justo, ut dignissim lectus. Cras tellus urna, dignissim eget metus congue, auctor tempus nulla. Duis nec velit scelerisque, cursus mauris nec, feugiat mauris. Proin laoreet tincidunt ex et vehicula. Mauris viverra et nisi ac fermentum. In eget sapien finibus, suscipit turpis eu, aliquam neque. Nunc sit amet risus a mauris tempus tempus. Proin sit amet ipsum aliquet, condimentum lorem at, ultrices diam. Nunc vehicula felis purus, et rutrum quam tincidunt at. Morbi rutrum, justo cursus luctus venenatis, elit lectus vehicula metus, in commodo quam arcu in sem.');">JQuery Online Alert - DANGER</button><br>
					<button style="background-color:yellow;color:black;padding:1em;width:600px;" onClick="getOA('warning|Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras in massa id lacus porta posuere. Nulla suscipit eget orci a facilisis. Sed feugiat interdum nibh vel bibendum. Nam condimentum ornare ante eget laoreet. Ut iaculis sem eu nibh porttitor vehicula. Vivamus nunc massa, accumsan at sodales vel, suscipit quis arcu. Vestibulum ac accumsan justo, ut dignissim lectus. Cras tellus urna, dignissim eget metus congue, auctor tempus nulla. Duis nec velit scelerisque, cursus mauris nec, feugiat mauris. Proin laoreet tincidunt ex et vehicula. Mauris viverra et nisi ac fermentum. In eget sapien finibus, suscipit turpis eu, aliquam neque. Nunc sit amet risus a mauris tempus tempus. Proin sit amet ipsum aliquet, condimentum lorem at, ultrices diam. Nunc vehicula felis purus, et rutrum quam tincidunt at. Morbi rutrum, justo cursus luctus venenatis, elit lectus vehicula metus, in commodo quam arcu in sem.');">JQuery Online Alert - WARNING</button><br>
					<button style="background-color:green;color:white;padding:1em;width:600px;" onClick="getOA('success|Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras in massa id lacus porta posuere. Nulla suscipit eget orci a facilisis. Sed feugiat interdum nibh vel bibendum. Nam condimentum ornare ante eget laoreet. Ut iaculis sem eu nibh porttitor vehicula. Vivamus nunc massa, accumsan at sodales vel, suscipit quis arcu. Vestibulum ac accumsan justo, ut dignissim lectus. Cras tellus urna, dignissim eget metus congue, auctor tempus nulla. Duis nec velit scelerisque, cursus mauris nec, feugiat mauris. Proin laoreet tincidunt ex et vehicula. Mauris viverra et nisi ac fermentum. In eget sapien finibus, suscipit turpis eu, aliquam neque. Nunc sit amet risus a mauris tempus tempus. Proin sit amet ipsum aliquet, condimentum lorem at, ultrices diam. Nunc vehicula felis purus, et rutrum quam tincidunt at. Morbi rutrum, justo cursus luctus venenatis, elit lectus vehicula metus, in commodo quam arcu in sem.');">JQuery Online Alert - SUCCESS</button><br>
					<button style="background-color:blue;color:white;padding:1em;width:600px;" onClick="getOA('default|Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras in massa id lacus porta posuere. Nulla suscipit eget orci a facilisis. Sed feugiat interdum nibh vel bibendum. Nam condimentum ornare ante eget laoreet. Ut iaculis sem eu nibh porttitor vehicula. Vivamus nunc massa, accumsan at sodales vel, suscipit quis arcu. Vestibulum ac accumsan justo, ut dignissim lectus. Cras tellus urna, dignissim eget metus congue, auctor tempus nulla. Duis nec velit scelerisque, cursus mauris nec, feugiat mauris. Proin laoreet tincidunt ex et vehicula. Mauris viverra et nisi ac fermentum. In eget sapien finibus, suscipit turpis eu, aliquam neque. Nunc sit amet risus a mauris tempus tempus. Proin sit amet ipsum aliquet, condimentum lorem at, ultrices diam. Nunc vehicula felis purus, et rutrum quam tincidunt at. Morbi rutrum, justo cursus luctus venenatis, elit lectus vehicula metus, in commodo quam arcu in sem.');">JQuery Online Alert - INFORMATION</button><br>
					<a href="php/index.php" target="_blank"><button style="background-color:white;color:black;padding:1em;width:600px;">Administration (PHP)</button></a>
				</center>
			</td>
		</tr>
	</table>
	
	<script type="text/javascript" src="js/jquery-2.1.4.min.js"></script>
	<script type="text/javascript" src="js/jqueryOA.js"></script>
</body>